services:
    fimiz_chat_api_server_1:
        container_name: fimiz_chat_api_server_container_1
        image: fimiz/chat:latest
        ports:
            - 1111:8080
        environment:
            - PORT=8080
            - PG_DB_PASSWORD=${PG_DB_PASSWORD}
            - PG_DB_USERNAME=${PG_DB_USERNAME}
            - PG_DB_HOST=${PG_DB_HOST}
            - PG_DB_NAME=${PG_DB_NAME}
    fimiz_chat_api_server_2:
        container_name: fimiz_chat_api_server_container_2
        image: fimiz/chat:latest
        ports:
            - 2222:8080
        environment:
              - PORT=8080
              - PG_DB_PASSWORD=${PG_DB_PASSWORD}
              - PG_DB_USERNAME=${PG_DB_USERNAME}
              - PG_DB_HOST=${PG_DB_HOST}
              - PG_DB_NAME=${PG_DB_NAME}
    fimiz_chat_api_server_3:
        container_name: fimiz_chat_api_server_container_3
        image: fimiz/chat:latest
        ports:
            - 3333:8080
        environment:
              - PORT=8080
              - PG_DB_PASSWORD=${PG_DB_PASSWORD}
              - PG_DB_USERNAME=${PG_DB_USERNAME}
              - PG_DB_HOST=${PG_DB_HOST}
              - PG_DB_NAME=${PG_DB_NAME}
    nginx:
        container_name: nginx_container
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - fimiz_chat_api_server_1
            - fimiz_chat_api_server_2
            - fimiz_chat_api_server_3
