services:
    fimiz_socket_1:
        container_name: fimiz_socket_container_1
        image: fimiz-socket
        ports:
            - 3001:3001
        environment:
            - PORT=3001
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
    fimiz_socket_2:
        container_name: fimiz_socket_container_2
        image: fimiz-socket
        ports:
            - 3002:3002
        environment:
            - PORT=3002
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
    fimiz_socket_3:
        container_name: fimiz_socket_container_3
        image: fimiz-socket
        ports:
            - 3003:3003
        environment:
            - PORT=3003
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
    nginx:
        container_name: fimiz_socket_nginx_container
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        ports:
            - 3000:80
        depends_on:
            - fimiz_socket_1
            - fimiz_socket_2
            - fimiz_socket_3
